import Head from 'next/head';
import Navbar from './navbar';
import Onboarding from './onboarding/onboarding';


const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        {/* <ProgressionTabs /> */}
        <Onboarding />
      </main>
    </>
  );
}

export default Home;